services:
  web:
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8090:8080"
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    depends_on:
      db:
        condition: service_healthy

  api:
    image: mempool/backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MEMPOOL_BACKEND: "none"
      MEMPOOL_NETWORK: "signet"
      MEMPOOL_POLL_RATE_MS: "1000"
      CORE_RPC_HOST: "host.docker.internal"
      CORE_RPC_PORT: "38332"
      CORE_RPC_USERNAME: "satoshi"
      CORE_RPC_PASSWORD: "nakamoto"
      CORE_RPC_TIMEOUT: "60000"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.5.21
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
      MARIADB_AUTO_UPGRADE: "1"
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mempool", "-pmempool"]
      interval: 5s
      timeout: 5s
      retries: 10
